// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduler.DataAccess;

#nullable disable

namespace Scheduler.DataAccess.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    [Migration("20240706145501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scheduler.Core.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General Manager"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trainer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shift Lead"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Team Member"
                        });
                });

            modelBuilder.Entity("Scheduler.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsecutiveDaysWorked")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoggedInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinutesWorked")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsecutiveDaysWorked = 0,
                            CreationDate = new DateTime(2024, 7, 6, 10, 55, 0, 789, DateTimeKind.Local).AddTicks(4390),
                            Email = "sam.tumaus@gmail.com",
                            FirstName = "Sam",
                            IsAdmin = true,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            LastLoggedInDate = new DateTime(2024, 7, 6, 10, 55, 0, 789, DateTimeKind.Local).AddTicks(4434),
                            LastName = "Tumaus",
                            MinutesWorked = 0,
                            Password = "$2a$10$eYEGsyyqwJMy79DJ6LHkquoLrCEpDys5HOSK0Hl3wfZoQly3cg7YO",
                            PhoneNumber = "302-507-9985",
                            Status = 0,
                            Title = "Manager",
                            TitleId = 2,
                            UpdateDate = new DateTime(2024, 7, 6, 10, 55, 0, 789, DateTimeKind.Local).AddTicks(4432),
                            Username = "default-admin"
                        },
                        new
                        {
                            Id = 2,
                            ConsecutiveDaysWorked = 0,
                            CreationDate = new DateTime(2024, 7, 6, 10, 55, 0, 858, DateTimeKind.Local).AddTicks(8235),
                            Email = "dillon.sean@gmail.com",
                            FirstName = "Dillon",
                            IsAdmin = false,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            LastLoggedInDate = new DateTime(2024, 7, 6, 10, 55, 0, 858, DateTimeKind.Local).AddTicks(8278),
                            LastName = "Sean",
                            MinutesWorked = 0,
                            Password = "$2a$10$DShY.dFtFjum.XQftTQ3G.GMIzWcIGf8912sfDLA6aWiQPNrOCUqe",
                            PhoneNumber = "302-627-9281",
                            Status = 0,
                            Title = "Team Member",
                            TitleId = 5,
                            UpdateDate = new DateTime(2024, 7, 6, 10, 55, 0, 858, DateTimeKind.Local).AddTicks(8277),
                            Username = "test-team-member"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
